# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guess.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bguess.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1d\n\x0cGuessRequest\x12\r\n\x05guess\x18\x01 \x01(\x05\"\xa0\x01\n\rGuessResponse\x12*\n\x06result\x18\x01 \x01(\x0e\x32\x1a.GuessResponse.GuessResult\x12\x0e\n\x06winner\x18\x02 \x01(\x05\"S\n\x0bGuessResult\x12\x1c\n\x18GUESS_RESULT_UNSPECIFIED\x10\x00\x12\x0b\n\x07TOO_LOW\x10\x01\x12\x0c\n\x08TOO_HIGH\x10\x02\x12\x0b\n\x07\x43ORRECT\x10\x03\x32:\n\x0cGuessingGame\x12*\n\x05Guess\x12\r.GuessRequest\x1a\x0e.GuessResponse\"\x00(\x01\x42\x13\n\x11org.example.stubsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guess_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021org.example.stubs'
  _GUESSREQUEST._serialized_start=48
  _GUESSREQUEST._serialized_end=77
  _GUESSRESPONSE._serialized_start=80
  _GUESSRESPONSE._serialized_end=240
  _GUESSRESPONSE_GUESSRESULT._serialized_start=157
  _GUESSRESPONSE_GUESSRESULT._serialized_end=240
  _GUESSINGGAME._serialized_start=242
  _GUESSINGGAME._serialized_end=300
# @@protoc_insertion_point(module_scope)
