# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guess.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bguess.proto\"/\n\x0cGuessRequest\x12\r\n\x05guess\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\")\n\x06Result\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06winner\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2g\n\x05Guess\x12\x1c\n\x05Start\x12\x06.Empty\x1a\x07.Result\"\x00\x30\x01\x12%\n\x05Guess\x12\r.GuessRequest\x1a\x07.Result\"\x00(\x01\x30\x01\x12\x19\n\x04Stop\x12\x06.Empty\x1a\x07.Result\"\x00\x42\x13\n\x11org.example.stubsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guess_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021org.example.stubs'
  _GUESSREQUEST._serialized_start=15
  _GUESSREQUEST._serialized_end=62
  _RESULT._serialized_start=64
  _RESULT._serialized_end=105
  _EMPTY._serialized_start=107
  _EMPTY._serialized_end=114
  _GUESS._serialized_start=116
  _GUESS._serialized_end=219
# @@protoc_insertion_point(module_scope)
